include:
  - /templates.gitlab-ci.yaml
  - /jobs/build_job.julia-1.0.gitlab-ci.yaml
  - /jobs/build_job.julia-1.3.gitlab-ci.yaml
  - /jobs/build_jobs.gitlab-ci.yaml
  - /jobs/build_job.julia-1.gitlab-ci.yaml
  - /jobs/test_jobs.julia-1.0.gitlab-ci.yaml
  - /jobs/test_jobs.julia-1.3.gitlab-ci.yaml
  - /jobs/test_jobs.gitlab-ci.yaml
  - /jobs/test_jobs.julia-1.gitlab-ci.yaml
  - /jobs/test_jobs-with_reports.julia-1.3.gitlab-ci.yaml
  - /jobs/test_jobs-with_reports.gitlab-ci.yaml
  - /jobs/test_jobs-with_reports.julia-1.gitlab-ci.yaml

stages:
  - build
  - test

variables:
  JULIA_PROJECT_PATH: examples/Sample
