include: .gitlab-ci_template.yaml

.sample:
  before_script:
    - !reference [.gitlab.redirect_git_for_ci_server_host, before_script]
    - cd examples/Sample

build:1.0:
  extends:
    - .julia:1.0
    - .sample
    - .julia.build

build:1.3:
  extends:
    - .julia:1.3
    - .sample
    - .julia.build

build:1.6:
  extends:
    - .julia:1.6
    - .sample
    - .julia.build

build:1.7:
  extends:
    - .julia:1.7
    - .sample
    - .julia.build

test:1.0:
  extends:
    - .julia:1.0
    - .sample
    - .julia.test
  needs: ["build:1.0"]

test:1.3:
  extends:
    - .julia:1.3
    - .sample
    - .julia.test.with_reports
  needs: ["build:1.3"]

test:1.6:
  extends:
    - .julia:1.6
    - .sample
    - .julia.test.with_reports
  needs: ["build:1.6"]

test:1.7:
  extends:
    - .julia:1.7
    - .sample
    - .julia.test.with_reports
  needs: ["build:1.7"]

test.with_threads:1.0:
  extends:
    - .julia:1.0
    - .sample
    - .julia.test.with_threads
  needs: ["build:1.0"]

test.with_threads:1.3:
  extends:
    - .julia:1.3
    - .sample
    - .julia.test.with_threads
  needs: ["build:1.3"]

test.with_threads:1.6:
  extends:
    - .julia:1.6
    - .sample
    - .julia.test.with_threads
  needs: ["build:1.6"]

test.with_threads:1.7:
  extends:
    - .julia:1.7
    - .sample
    - .julia.test.with_threads
  needs: ["build:1.7"]

test.with_threads.with_reports:1.3:
  extends:
    - .julia:1.3
    - .sample
    - .julia.test.with_threads.with_reports
  needs: ["build:1.3"]

test.with_threads.with_reports:1.6:
  extends:
    - .julia:1.6
    - .sample
    - .julia.test.with_threads.with_reports
  needs: ["build:1.6"]

test.with_threads.with_reports:1.7:
  extends:
    - .julia:1.7
    - .sample
    - .julia.test.with_threads.with_reports
  needs: ["build:1.7"]
