include:
  - /templates.gitlab-ci.yaml
  - /jobs/build.julia-1.0.gitlab-ci.yaml
  - /jobs/build.julia-1.3.gitlab-ci.yaml
  - /jobs/build.gitlab-ci.yaml
  - /jobs/build.julia-1.gitlab-ci.yaml
  - /jobs/test.julia-1.0.gitlab-ci.yaml
  - /jobs/test.julia-1.3.gitlab-ci.yaml
  - /jobs/test.gitlab-ci.yaml
  - /jobs/test.julia-1.gitlab-ci.yaml
  - /jobs/test-with_reports.julia-1.3.gitlab-ci.yaml
  - /jobs/test-with_reports.gitlab-ci.yaml
  - /jobs/test-with_reports.julia-1.gitlab-ci.yaml

stages:
  - build
  - test

variables:
  JULIA_PROJECT_PATH: examples/Sample
