include:
  - /templates.gitlab-ci.yaml
  - /jobs/build.julia-1.0.gitlab-ci.yaml
  - /jobs/build.julia-1.1.gitlab-ci.yaml
  - /jobs/build.julia-1.2.gitlab-ci.yaml
  - /jobs/build.julia-1.3.gitlab-ci.yaml
  - /jobs/build.julia-1.4.gitlab-ci.yaml
  - /jobs/build.julia-1.5.gitlab-ci.yaml
  - /jobs/build.julia-lts.gitlab-ci.yaml
  - /jobs/build.julia-stable.gitlab-ci.yaml
  - /jobs/build.julia-1.gitlab-ci.yaml

  - /jobs/test.julia-1.0.gitlab-ci.yaml
  - /jobs/test.julia-1.1.gitlab-ci.yaml
  - /jobs/test.julia-1.2.gitlab-ci.yaml
  - /jobs/test.julia-1.3.gitlab-ci.yaml
  - /jobs/test.julia-1.4.gitlab-ci.yaml
  - /jobs/test.julia-1.5.gitlab-ci.yaml
  - /jobs/test.julia-lts.gitlab-ci.yaml
  - /jobs/test.julia-stable.gitlab-ci.yaml
  - /jobs/test.julia-1.gitlab-ci.yaml

stages:
  - build
  - test

variables:
  CI_JULIA_PROJECT_PATH: examples/Sample

test_variants:
  stage: test
  parallel:
    matrix:
      - CI_JULIA_VERSION: ["1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1"]
        CI_JULIA_TEST_REPORTS: ["REPORTS_OFF", "REPORTS_ON"]
        CI_JULIA_TEST_THREADS: ["THREADS_OFF", "THREADS_ON"]
  except:
    variables:
      - $CI_JULIA_TEST_REPORTS == "REPORTS_ON" && $CI_JULIA_TEST_THREADS == "THREADS_ON"
  trigger:
    include:
      - /templates.gitlab-ci.yaml
      - /jobs/build.gitlab-ci.yaml
      - /jobs/test.gitlab-ci.yaml
    strategy: depend
  needs: []
