# include: /templates.gitlab-ci.yaml

test-with_reports.julia-1.7:
  variables:
    JULIA_TEST_WITH_THREADS: "false"
    JULIA_TEST_WITH_REPORTS: "true"
  extends:
    - .julia.julia-image:1.7
    - .julia.test
