# include: /templates.gitlab-ci.yaml

test:1.3:
  extends:
    - .julia:1.3
    - .julia.test.with_reports
test.with_threads:1.3:
  extends:
    - .julia:1.3
    - .julia.test.with_threads.with_reports
