# include: /templates.gitlab-ci.yaml

test.julia-1.3:
  variables:
    JULIA_TEST_WITH_THREADS: "false"
    JULIA_TEST_WITH_REPORTS: "false"
  extends:
    - .julia.julia-image:1.3
    - .julia.test
  needs:
    - job: build.julia-1.3
      optional: true
